### ISSUE TITLE
Support for explicitly marking it as ok to merge

### ISSUE THREAD

**Issue by tomkerkhove** [ahmed-taj/dep#22]
This app checks PRs & issues that are referenced and decides based on the status.
However, in certain cases it is ok to merge it in and would be great to be able to flag it as ok.

Example - Issue is linked but not closed yet because it needs this PR:
![image](https://user-images.githubusercontent.com/4345663/41817752-405132c0-77a1-11e8-94ad-cc82866c387b.png)

DEP is blocking this as it detects this as depending on it given it's still open.

**Comment by z0al** [comment]
Hi @tomkerkhove , thanks for opening this ✨ 

Well, I'm confused. 

In the example (pic) you provided, the app should not mark **#31** as a dependency. The app only considers `depends on #number` pattern. 

https://github.com/ahmed-taj/dep/blob/999cc9bf74059404321d8323403c7ffac38f9a05/lib/helpers/match.js#L1

Again in the picture above, the app didn't report the final status yet, it supposed to report it shortly which I guess didn't happen. As far as I can tell, the app probably failed somewhere due to the current [environment restrictions](https://zeit.co/pricing) (Free plan).

**Comment by tomkerkhove** [comment]
That's interesting. Is there a way to see if that is the case because I only did 2 PRs in one week for this repo, maybe 10 for my account.

**Comment by z0al** [comment]
would you be able to provide more a link to the PR above? I might be able to check what's exactly going on

**Comment by tomkerkhove** [comment]
Unfortunately not given it has NDA content but it's ok for now, will circle back here when it's public (3-4w)

**Comment by z0al** [comment]
I think #26 should fix this too. Closing this now, but please feel free to reopen if it's still there. Thanks for reporting :)
