### ISSUE TITLE
Don't require a / in the beginning

### ISSUE THREAD

**Issue by nesl247** [ahmed-taj/dep#3]
It would be nice if we could simply write the following anywhere in a comment: `Depends on #something, #something, and #something` and it would work. Writing a slash command in a comment feels weird.

**Comment by ryanhiebert** [comment]
I'd like this, so that it matches the way GitHub will notice special references to other issues (aka `Fixes #42`). When doing this, we probably also would want to allow alternative tense, like `depend` and `depended`, to match how GitHub handles the `fix`, `close`, and `resolve` keywords to automatically close issues when a related pull request is merged.
