### ISSUE TITLE
Status not changing to pending 

### ISSUE THREAD

**Issue by ibakshay** [ahmed-taj/dep#30]
Hi, `#234` is a open issue but still the PR status is coming as `Success` instead of `Pending`. (when dependency is not resolved). Could you please check If something is missing ?. I tried with both open  pull request and issues. In Both the cases. the  Pr status is not coming as Pending. 
<img width="901" alt="Screen Shot 2019-08-04 at 04 27 19" src="https://user-images.githubusercontent.com/33329946/62418707-3eefb500-b670-11e9-9f4b-01930941880b.png">

**Comment by ibakshay** [comment]
I don't think `Depends on` is a keyboard anymore. Can you please check and propose a possible solution ?. It would be great.

**Comment by ibakshay** [comment]
My bad, I commented instead of giving in PR description. It is working perfectly fine.  Thanks for the wonderful project. Could you please tell a little bit about the probot-metadata ?. Because I am working on POC and I  have a use case for storing data in `probot-metadata`. I can see that you are not storing data in Metadata anymore though.

**Comment by z0al** [comment]
> Could you please tell a little bit about the probot-metadata ?

The bot used to allow declaring dependencies in comments and I needed a way to store issue numbers, and that's why I used `probot-metadata`.

Later, I decided to stick only to PR description (see #11 for details) which made `probot-metadata` unnecessary (since I can just apply a regular expression to the PR description to get the list of dependencies).

Thanks for using Dep
